import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";
import { getRecentMemories } from "../data/db.js";

export async function generateProofOfTradingPDF(
  vaultName: string,
): Promise<string> {
  return new Promise(async (resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const fileName = `NeuroLoom_Report_${Date.now()}.pdf`;

      // Simpan sementara di root folder backend sebelum dikirim ke frontend
      const filePath = path.resolve(process.cwd(), fileName);
      const writeStream = fs.createWriteStream(filePath);

      doc.pipe(writeStream);

      // --- HEADER LAPORAN ---
      doc
        .fontSize(20)
        .font("Helvetica-Bold")
        .text("NeuroLoom Vault: Proof of Trading", { align: "center" });
      doc.moveDown();
      doc.fontSize(12).font("Helvetica").text(`Vault Strategy : ${vaultName}`);
      doc.text(`Generated At   : ${new Date().toISOString()}`);
      doc.text(`Network        : BSC Testnet`);
      doc.moveDown(2);

      // --- TARIK DATA DATABASE ---
      const histories = await getRecentMemories(15); // Ambil 15 log terakhir

      if (histories.length === 0) {
        doc
          .font("Helvetica-Oblique")
          .text("Belum ada data historis eksekusi pada Vault ini.");
      } else {
        doc
          .fontSize(14)
          .font("Helvetica-Bold")
          .text("Historical Execution Log:", { underline: true });
        doc.moveDown();

        histories.forEach((trade, index) => {
          // Baris Info Utama
          doc
            .fontSize(10)
            .font("Helvetica-Bold")
            .text(`[${index + 1}] Date: ${trade.timestamp}`);
          doc
            .font("Helvetica")
            .text(
              `Action: ${trade.action} | Executed Price: $${trade.executedPrice} | RSI: ${trade.rsiAtExecution}`,
            );
          doc.text(`Status: ${trade.status}`);
          doc.moveDown(0.5);

          // Baris Analisis AI (Thoughts)
          doc
            .font("Helvetica-Oblique")
            .text(`AI Reasoning:\n${trade.reasoning}`, {
              width: 500,
              align: "justify",
            });
          doc.moveDown(1.5);
        });
      }

      // --- FOOTER ---
      doc.moveDown(2);
      doc
        .fontSize(9)
        .font("Helvetica")
        .fillColor("gray")
        .text(
          "This document is automatically generated by NeuroLoom AI Quant Agent. Cryptographic proof is stored on-chain.",
          { align: "center" },
        );

      doc.end();

      writeStream.on("finish", () => resolve(filePath));
      writeStream.on("error", reject);
    } catch (error) {
      reject(error);
    }
  });
}
